# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Squares number
#' @param i number to square
test_me <- function(i) {
    .Call(`_PANPRSnext_test_me`, i)
}

#' Gets eigen values
#' @param M Matrix to get eigen values for
getEigenValues <- function(M) {
    .Call(`_PANPRSnext_getEigenValues`, M)
}

