# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main CPP function
#' @param summary_betas matrix
#' @param ld_J vector
#' @param num_iter_vec vector
#' @param index_matrix matrix
#' @param index_J vector
#' @param ld_vec vector
#' @param upper_val double
#' @param SD_vec matrix
#' @param tuning_matrix matrix
#' @param beta_matrix matrix
#' @param lambda0_vec vector
#' @param z_matrix matrix
#' @param all_tuning_matrix matrix
#' @param lambda_vec_func vector
#' @param func_lambda matrix
#' @param Ifunc_SNP vector
#' @param dims vector
#' @param params vector
gsfPEN_cpp <- function(summary_betas, ld_J, num_iter_vec, index_matrix, index_J, ld_vec, upper_val, SD_vec, tuning_matrix, beta_matrix, lambda0_vec, z_matrix, all_tuning_matrix, lambda_vec_func, func_lambda, Ifunc_SNP, dims, params) {
    .Call(`_PANPRSnext_gsfPEN_cpp`, summary_betas, ld_J, num_iter_vec, index_matrix, index_J, ld_vec, upper_val, SD_vec, tuning_matrix, beta_matrix, lambda0_vec, z_matrix, all_tuning_matrix, lambda_vec_func, func_lambda, Ifunc_SNP, dims, params)
}

